# Dockerfile.base
FROM python:3.10-slim


WORKDIR /app

# Install the Python dependencies
COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt